### ISSUE TITLE
npm install fails without force option

### ISSUE THREAD

**Issue by yagizsenal** [rarity-adventure/rarity-frontend#2] opened 2021-09-08 14:10 UTC
After cloning the project I ran `npm install`. This is the error result I got:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @rarity/frontend@1.0.0
npm ERR! Found: postcss@7.0.35
npm ERR! node_modules/postcss
npm ERR!   postcss@"7.0.35" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.0.0" from @fullhuman/postcss-purgecss@4.0.3
npm ERR! node_modules/@fullhuman/postcss-purgecss
npm ERR!   @fullhuman/postcss-purgecss@"4.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2021-09-08T13_59_28_136Z-debug.log
```

`npm --version` returns `7.22.0`.

Is this an error related with my setup?

**Comment by yagizsenal** [comment] 2021-09-08 17:07
I have seen that same problem exists in the repo where this template is from (sushi-frontend), therefore this is not a issue with my setup. However, it would be nice not to use `--force` when installing npm packages.

**Comment by eabz** [comment] 2021-09-08 20:38
Have you tried `yarn` ?

**Comment by helloitsm3** [comment] 2021-09-09 10:20
I can confirm that using ```yarn``` will remove the error you're experiencing when using ```npm```

**Comment by eabz** [comment] 2021-09-12 02:44
Since we use yarn for development, we won't fix this.

**Closed by eabz** 2021-09-12 02:44 UTC
